version: "3.7"

services:
  back:
    container_name: back
    hostname: back
    build: back
    env_file:
      - real_time.env
    ports:
      - "8000:8000"
    networks:
      - realtime
    depends_on:
      - rabbitmq

#  telebot:
#    build: telebot
#    env_file:
#      - real_time.env
#    networks:
#      - realtime

  rabbitmq:
    image: rabbitmq:3.8.9-management
    hostname: rabbitmq
    container_name: rabbitmq
    volumes:
      - ./rabbitmq/data/:/var/lib/rabbitmq/
      - ./rabbitmq/log/:/var/log/rabbitmq/
      - ./rabbitmq/etc/:/etc/rabbitmq/
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - realtime

  mongo:
    image: mongo:4.2.3-bionic
    hostname: mongodb
    container_name: mongodb
    ports:
        - 27018:27017
    volumes:
        - mongodb:/data/db
    networks:
      - realtime
  
  crawler:
    container_name: crawler
    build: crawlers
    environment:
      RABBIT_HOSTNAME: rabbitmq
    ports:
        - 8020:8020
    depends_on:
      - rabbitmq
    networks:
      - realtime

  crawler_consumer:
    container_name: crawler_consumer
    build: crawlers_consumer
    environment:
      RABBIT_HOSTNAME: rabbitmq
      MONGO_HOSTNAME: mongodb
    depends_on:
      - mongo
      - rabbitmq
    restart: always
    networks:
      - realtime
    
volumes:
    mongodb:

networks:
  realtime: { }
