SOURCES = [
    {'label': 'all', 'value': '__all__'},
    {'label': 'ria.ru', 'value': 'ria.ru'},
    {'label': 'bbc', 'value': 'bbc'},
    {'label': 'fontanka', 'value': 'fontanka'},
    {'label': 'gazeta.ru', 'value': 'gazeta.ru'},
    {'label': 'meduza.io', 'value': 'meduza.io'},
    {'label': 'intefrax', 'value': 'intefrax'},
    {'label': 'izvestia', 'value': 'izvestia'},
    {'label': 'kommersant', 'value': 'kommersant'},
    {'label': 'lenta.ru', 'value': 'lenta.ru'},
    {'label': 'rambler', 'value': 'rambler'},
    {'label': 'rbk', 'value': 'rbk'},
    {'label': 'rg', 'value': 'rg'},
    {'label': 'russian_rt', 'value': 'russian_rt'},
    {'label': 'tass.ru', 'value': 'tass.ru'},
    {'label': 'tj', 'value': 'tj'},
    {'label': 'vz', 'value': 'vz'},
    {'label': 'yanews', 'value': 'yanews'},
]

LABELS = [
    {'label': 'not_news', 'value': 'not_news'},
    {'label': 'sports', 'value': 'sports'},
    {'label': 'society', 'value': 'society'},
    {'label': 'economy', 'value': 'economy'},
    {'label': 'entertainment', 'value': 'entertainment'},
    {'label': 'other', 'value': 'other'},
    {'label': 'science', 'value': 'science'},
    {'label': 'technology', 'value': 'technology'},
]
